# pull official base image
FROM python:3.9.0-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV APP_HOME=/usr/src/backend

# create the appropriate directories
RUN mkdir $APP_HOME $APP_HOME/staticfiles $APP_HOME/mediafiles
WORKDIR $APP_HOME

# install dependencies
ADD ./backend/Pipfile* $APP_HOME/
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && pip install --upgrade pip \
    && pip install --upgrade pipenv \
    && pipenv install --skip-lock --system --dev \
    && apk del build-deps

# copy(add) script
COPY ./backend/scripts/start.dev.sh /

# copy(add) project
ADD ./backend $APP_HOME/